### ISSUE TITLE
Doesn't appear to work with gatsby-source-wordpress-experimental

### ISSUE THREAD

**Issue by eurobob** [g00glen00b/gatsby-wordpress-reading-time#6]
node.content is not present even though the post type has content

**Comment by g00glen00b** [comment]
True, this plugin uses the structure returned by the old gatsby-source-wordpress plugin. Sadly I have shifted away from WordPress so it's difficult for me to continue working on this plugin. I reccommend using other plugins like https://www.npmjs.com/package/gatsby-plugin-readingtime (which should be applicable to all source plugins).
